[project]
name = "neat-jax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.1",
    "jax>=0.7.1",
    "slimevolleygym>=0.1.0",
]
